version: '3.2'

services:
  php:
    build:
      context: ./docker/php
      args:
        - INSTALL_XDEBUG=${PHP_INSTALL_XDEBUG}
        - INSTALL_PHPREDIS=${PHP_INSTALL_PHPREDIS}
    image: wheremycashat/php
    volumes: &base_volume
      - type: volume
        source: ./application
        target: /var/www/html
    networks:
      - wheremycashat_network
  
  nginx:
    depends_on:
      - php
    build:
      context: ./docker/nginx
    image: wheremycashat/nginx
    volumes: *base_volume
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
    networks:
      - wheremycashat_network

  mariadb:
    build:
      context: ./docker/mariadb
    image: docker/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MARIADB_DATABASE}"
      MYSQL_USER: "${MARIADB_USER}"
      MYSQL_PASSWORD: "${MARIADB_PASSWORD}"
    networks:
      - wheremycashat_network

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - wheremycashat_network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: "mariadb"
      PMA_USER: "root"
      PMA_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
    ports:
      - "${PMA_PORT}:80"
    volumes:
      - pma_session:/sessions
    networks:
      - wheremycashat_network

networks:
  wheremycashat_network:
    driver: "bridge"

volumes:
  mariadb_data:
  redis_data:
  pma_session:
